name: Build Windows EXE
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pyinstaller pillow pyqt6
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed main.py ^
            --add-data "config.json;." ^
            --add-data "images;images"
          dir dist
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-annotator-exe
          path: dist/main.exe
